# Generated by Django 4.2.7 on 2023-11-16 19:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("whoAmI", models.CharField(max_length=20000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100000)),
                ("created_date", models.DateTimeField(default=datetime.datetime.now)),
                (
                    "author",
                    models.CharField(
                        choices=[("User", "User"), ("Bot", "Bot")],
                        default="User",
                        max_length=15,
                    ),
                ),
                ("telegram_message_id", models.BigIntegerField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("TelegramText", "Telegram Text"),
                            ("TelegramVoice", "Telegram Voice"),
                        ],
                        default="TelegramText",
                        max_length=15,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="gptizer.user",
                    ),
                ),
            ],
        ),
    ]
